# Generated by Django 4.1.3 on 2022-11-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=13, verbose_name='license_plate')),
                ('vin_code', models.CharField(max_length=15, verbose_name='vin_code')),
                ('client', models.CharField(max_length=250, verbose_name='client')),
            ],
            options={
                'ordering': ['client', 'license_plate'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=250, verbose_name='maker')),
                ('car_model', models.CharField(max_length=250, verbose_name='car_model')),
            ],
            options={
                'verbose_name': 'marke',
                'ordering': ['maker', 'car_model'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('total_sum', models.FloatField(verbose_name='total_sum')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('price', models.FloatField(verbose_name='price')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.order')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='service_name')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['service_name'],
            },
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='automobilio_modelis',
        ),
        migrations.RemoveField(
            model_name='uzsakymas',
            name='automobilis',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='paslauga',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
        ),
        migrations.DeleteModel(
            name='AutomobilioModelis',
        ),
        migrations.DeleteModel(
            name='Automobilis',
        ),
        migrations.DeleteModel(
            name='Paslauga',
        ),
        migrations.DeleteModel(
            name='Uzsakymas',
        ),
        migrations.DeleteModel(
            name='UzsakymoEilute',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carmodel'),
        ),
    ]
