# Generated by Django 4.1.3 on 2022-11-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_remove_order_total_sum_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_code',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default=1, max_length=10, verbose_name='license plate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default=1, max_length=30, verbose_name='VIN number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.CharField(default=1, max_length=50, verbose_name='model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoservice.carmodel', verbose_name='car model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(max_length=100, verbose_name='client name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price'),
        ),
        migrations.DeleteModel(
            name='OrderEntry',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.service', verbose_name='service'),
        ),
    ]
