# Generated by Django 4.1.3 on 2022-11-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_orderline_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
            ],
            options={
                'verbose_name': 'entry of the order',
                'verbose_name_plural': 'entries of the order',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['client', 'license_plate'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make', 'car_model'], 'verbose_name': 'car model', 'verbose_name_plural': 'car models'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default=1, max_length=10, verbose_name='license_plate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vin_code',
            field=models.CharField(default=1, max_length=20, verbose_name='vin_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(default=1, max_length=50, verbose_name='car_model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default=1, max_length=50, verbose_name='service_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoservice.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(max_length=250, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderentry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.service', verbose_name='service'),
        ),
    ]
