# Generated by Django 4.1.3 on 2022-11-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_orderentry_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderentry',
            options={},
        ),
    ]
